version: '1.0'

services:
  db:
    image: postgres:latest
    volumes:
      - ./data-load/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pokemons_app